name: Release

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
jobs:
  call-workflow-check:
    uses: ./.github/workflows/check.yml

  publish:
    name: Build Binaries
    needs: call-workflow-check
    concurrency: ci-releasing-binaries
    strategy:
      matrix:
        build: [x86_64, x86_64-musl, macos]
        include:
        - build: x86_64
          os: ubuntu-latest
          target: x86_64-unknown-linux-gnu
          artifact_name: better_be
          asset_name: better_be-linux-x86_64
        - build: x86_64-musl
          os: ubuntu-latest
          target: x86_64-unknown-linux-musl
          artifact_name: better_be
          asset_name: better_be-linux-x86_64-musl
        - build: macos
          os: macos-latest
          target: aarch64-apple-darwin
          artifact_name: better_be
          asset_name: better_be-darwin-aarch64
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install Musl dependencies
        if: matrix.build == 'x86_64-musl'
        run: |
          sudo apt -y update
          sudo apt install -y musl musl-dev musl-tools

      - name: Setting rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}
          override: true
          profile: minimal

      - name: Using cache to speed up
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-stable-cargo-${{ hashFiles('**/Cargo.lock') }}
      
      - name: Build bianry
        run: cargo build --release

      - name: Upload binary to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/release/${{ matrix.artifact_name }}
          asset_name: ${{ matrix.asset_name }}
          tag: ${{ github.ref }}
